title: NOSE Cloud Architecture
description: NOSE is a proposal for a new cloud-native architecture that removes the burden of designing cloud applications with microservices and containers.
theme: jekyll-theme-cayman
